import { readFile, writeFile, mkdir, readdir, stat } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import path from 'node:path'
import postcss from 'postcss'
import tailwind from 'tailwindcss'
import autoprefixer from 'autoprefixer'
import cssnano from 'cssnano'
import * as esbuild from 'esbuild'
import scope from '../postcss/scope.js'

const root = path.resolve(import.meta.dirname, '..')
const dist = path.join(root, 'dist')
const dev = process.argv.includes('--dev')

async function componentDirs() {
  const base = path.join(root, 'components')
  if (!existsSync(base)) return []
  const out = []
  for (const name of await readdir(base)) {
    if ((await stat(path.join(base, name))).isDirectory()) out.push(name)
  }
  return out.sort()
}

async function buildCSS(names) {
  const parts = [await readFile(path.join(root, 'src/tokens.css'), 'utf8')]
  for (const n of names) {
    const f = path.join(root, 'components', n, 'component.css')
    if (existsSync(f)) parts.push(`/* ${n} */\n` + (await readFile(f, 'utf8')))
  }
  parts.push(await readFile(path.join(root, 'src/kit.css'), 'utf8'))

  const plugins = [tailwind, autoprefixer, scope({ wrapper: '.sk-root' })]
  if (!dev) plugins.push(cssnano({ preset: ['default', { discardComments: { removeAll: true } }] }))

  const res = await postcss(plugins).process(parts.join('\n\n'), { from: path.join(root, 'src/kit.css'), to: path.join(dist, 'kit.min.css') })
  await writeFile(path.join(dist, 'kit.min.css'), res.css)
  return res.css.length
}

async function buildJS(names) {
  // registry.js is generated so the bundle statically imports every component,
  // keeping it one request with no dynamic-import CORS surprises on jsDelivr.
  const imports = []
  const entries = []
  names.forEach((n, i) => {
    const js = path.join(root, 'components', n, 'component.js')
    const html = path.join(root, 'components', n, 'component.html')
    if (!existsSync(js) && !existsSync(html)) return
    const id = `c${i}`
    if (existsSync(js)) imports.push(`import * as ${id} from '../components/${n}/component.js'`)
    if (existsSync(html)) imports.push(`import ${id}_html from '../components/${n}/component.html'`)
    entries.push(`  ${JSON.stringify(n)}: { mount: ${existsSync(js) ? `${id}.mount` : 'null'}, html: ${existsSync(html) ? `${id}_html` : 'null'} }`)
  })
  const src = `// generated by scripts/build.mjs — do not edit\n${imports.join('\n')}\n\nexport const registry = {\n${entries.join(',\n')}\n}\n`
  await writeFile(path.join(root, 'src/registry.js'), src)

  await esbuild.build({
    entryPoints: [path.join(root, 'src/loader.js')],
    bundle: true,
    format: 'iife',
    target: ['es2019'],
    minify: !dev,
    sourcemap: dev,
    loader: { '.html': 'text' },
    outfile: path.join(dist, 'kit.min.js'),
    banner: { js: '/* sqsp-kit — https://github.com/fraser-svg/sqsp-kit */' },
  })
  return (await stat(path.join(dist, 'kit.min.js'))).size
}

const names = await componentDirs()
await mkdir(dist, { recursive: true })
const css = await buildCSS(names)
const js = await buildJS(names)
console.log(`built ${names.length} components — css ${(css / 1024).toFixed(1)}kb, js ${(js / 1024).toFixed(1)}kb`)
