// generated by scripts/build.mjs — do not edit
import * as c0 from '../components/hero-split/component.js'
import c0_html from '../components/hero-split/component.html'
import * as c1 from '../components/logo-marquee/component.js'
import c1_html from '../components/logo-marquee/component.html'
import * as c2 from '../components/mega-menu/component.js'

export const registry = {
  "hero-split": { mount: c0.mount, html: c0_html },
  "logo-marquee": { mount: c1.mount, html: c1_html },
  "mega-menu": { mount: c2.mount, html: null }
}
